# netlify.toml

[build]
  # Python 스크립트를 먼저 실행한 후, quarto render를 실행합니다.
  # 만약 genjson.py가 외부 라이브러리를 사용한다면,
  # command = "pip install -r requirements.txt && python genjson.py && quarto render" 로 변경하세요.
  command = "pip install -r requirements.txt && python genjson.py && quarto render"
  
  # Quarto의 결과물이 저장되는 디렉토리입니다.
  publish = "_site"

[build.environment]
  # 빌드 환경에서 사용할 Quarto와 Python 버전을 지정합니다.
  QUARTO_VERSION = "1.4.553"
  PYTHON_VERSION = "3.11"
