name: Scheduled genjson.py runner

on:
  # push:
  #   paths:
  #     - 'posts/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-genjson:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run genjson.py
        run: python genjson.py

      - name: Copy posts.json to _site
        run: mkdir -p _site && cp posts.json _site/posts.json

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render index.qmd
        run: quarto render index.qmd

      - name: Commit and push updated files
        if: github.ref == 'refs/heads/master'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add posts.json _site/posts.json index.html
          git commit -m "chore: update posts.json and re-render index.qmd [skip ci]" || echo "No changes to commit"
          git push
